 ## Tổng quan:
 một thư viện quan trọng trong ngôn ngữ lập trình Python, được sử dụng chủ yếu trong các phép tính khoa học và tính toán số học. NumPy cung cấp một cấu trúc dữ liệu mảng đa chiều (n-dimensional array) mạnh mẽ, cho phép thực hiện các phép toán số học, đại số tuyến tính, thống kê và xử lý mảng dữ liệu một cách hiệu quả.

## tại sao tính toán trong numpy lại nhanh hơn python cơ bản?
* Sử dụng mảng đa chiều để lưu trữ dữ liệu
* Phép toán được thực hiện trên toàn bộ mảng một lần, tránh sd vòng lặp for
* Viết bằng C hoặc Fortran : hiệu suất cao hơn Python
* Tối ưu hóa độ lệch bộ  nhớ đếm (cache)
* Broadcasting

# Numpy

In [2]:
import numpy as np

### Shape

#### shape có thể là nhiều chiều 2 3 4: 2 mtr 3x4

## Creating Numpy Arrays

In [7]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [8]:
a2 = np.array([[3.14,1,2],
             [4,5,6]])
a2

array([[3.14, 1.  , 2.  ],
       [4.  , 5.  , 6.  ]])

##### chuyển về 1 kiểu dữ liệu lớn hơn


In [5]:
#cụ thể hóa kiểu dl
np.array([1,2,3,4],dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [9]:
type(a1)
type(a2)

numpy.ndarray

In [12]:
a2.shape

(2, 3)

In [13]:
a2.ndim

2

In [14]:
# kiểu dl thành phần bên trong
a2.dtype 

dtype('float64')

In [15]:
# tổng số phần tử
a2.size

6

## Creating from Scratch

In [1]:
# zeros 
y =  np.zeros([2,4])
y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
# ones
np.ones([3,4], dtype = str)

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [18]:
#ARANGE
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
#Full
np.full((3,5), 11)

array([[11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11]])

In [6]:
#linspace
np.linspace(5,25)

array([ 5.        ,  5.40816327,  5.81632653,  6.2244898 ,  6.63265306,
        7.04081633,  7.44897959,  7.85714286,  8.26530612,  8.67346939,
        9.08163265,  9.48979592,  9.89795918, 10.30612245, 10.71428571,
       11.12244898, 11.53061224, 11.93877551, 12.34693878, 12.75510204,
       13.16326531, 13.57142857, 13.97959184, 14.3877551 , 14.79591837,
       15.20408163, 15.6122449 , 16.02040816, 16.42857143, 16.83673469,
       17.24489796, 17.65306122, 18.06122449, 18.46938776, 18.87755102,
       19.28571429, 19.69387755, 20.10204082, 20.51020408, 20.91836735,
       21.32653061, 21.73469388, 22.14285714, 22.55102041, 22.95918367,
       23.36734694, 23.7755102 , 24.18367347, 24.59183673, 25.        ])

In [98]:
#IDENTITY : ma trận đơn vị
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [99]:
#EYE : tạo ma trận đơn vị không nhất thiết đg chéo chính
#.eye(kích thước hàng mtđv,kích thước cột mtđv(mặc định là kt hàng),vị trí bắt đầu của đg chéo = 1)
np.eye(5, k = 2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Random

In [6]:
# trả về số ngẫu nhiên từ phân phối đề trên khoảng [0;1)
np.random.random((4,4))

array([[0.88601409, 0.73743577, 0.18180228, 0.13938099],
       [0.94569498, 0.35265358, 0.03846134, 0.99841852],
       [0.57819383, 0.26018961, 0.31653502, 0.91687636],
       [0.66945656, 0.90917819, 0.87889189, 0.17854273]])

In [8]:
# Seed : random giống nhau
np.random.seed(0)
np.random.random((4,4))


array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [9]:
# Cũng trả về giá trị ngẫu nhiên từ phân phối đề [0;1) từ shape được chỉ định
np.random.rand(4,4)

array([[0.07403232, 0.74489355, 0.02728798, 0.35102223],
       [0.06496242, 0.05003045, 0.8318439 , 0.40387889],
       [0.45807054, 0.68437329, 0.58583341, 0.69533364],
       [0.77673882, 0.74468966, 0.91197149, 0.64606559]])

In [23]:
# Tạo ra các số ngẫu nhiên từ phân phối chuẩn có trung bình (mean) và độ lệch chuẩn(standard deviation) được chỉ định
np.random.normal(0,1,(3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [24]:
#random những số int trong khoảng(không bao gồm số high)
np.random.randint(0,100,(5,5))

array([[55, 28, 34,  0,  0],
       [36, 53,  5, 38, 17],
       [79,  4, 42, 58, 31],
       [ 1, 65, 41, 57, 35],
       [11, 46, 82, 91,  0]])

## Array Indexing & Slicing
### 1-d subarray

In [28]:
x1 = np.random.randint(20,size = 6)
x1

array([10, 13, 16,  7,  9,  0])

In [30]:
x1[1],x1[-1]

(13, 0)

### multi-d

In [9]:
x2 = np.random.randint(10,size = (3,4))
x2

array([[3, 0, 3, 5],
       [0, 2, 3, 8],
       [1, 3, 3, 3]])

In [32]:
x2[2][2]

1

In [33]:
x2[2,2] = 11
x2

array([[ 2,  7,  2,  9],
       [ 2,  3,  3,  2],
       [ 3,  4, 11,  2]])

## Slicing
### x[start:stop:step]

In [34]:
x1

array([10, 13, 16,  7,  9,  0])

In [35]:
x1[0:3]

array([10, 13, 16])

In [37]:
#step = 2
x1[::2]

array([10, 16,  9])

In [10]:
# hàng. cột
x2[:2,:3]

array([[3, 0, 3],
       [0, 2, 3]])

In [12]:
x2

array([[3, 0, 3, 5],
       [0, 2, 3, 8],
       [1, 3, 3, 3]])

In [11]:
x2[:,:3]

array([[3, 0, 3],
       [0, 2, 3],
       [1, 3, 3]])

## Reshaping of Array & Transpose

In [13]:
grid = np.arange(1,10)
grid


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
grid =  grid.reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
x = np.array([1,2,3])

In [47]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [48]:
#transpose: chuyển vị
x = np.transpose(x)
x

array([1, 2, 3])

In [56]:
# flatten: chuyển thành vecto 1 chiều
g1 = grid.flatten()
g1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
g2 = grid.flatten(order = 'F')
g2

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

## Array Concatenation and Splitting

In [16]:
x = np.array([[1,2,3],
            [4,5,6]])
y = np.array([[6,5,4],
             [2,3,1]])
np.concatenate((x,y))

array([[1, 2, 3],
       [4, 5, 6],
       [6, 5, 4],
       [2, 3, 1]])

In [8]:
np.concatenate((x,y),axis = 1)

array([[1, 2, 3, 6, 5, 4],
       [4, 5, 6, 2, 3, 1]])

In [18]:
#vstack : xếp theo chiều dọc
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                [6,5,4]])
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [19]:
#hstack : xếp theo chiều ngang
y = np.array([[11],
             [66]])
np.hstack((y,grid))

array([[11,  9,  8,  7],
       [66,  6,  5,  4]])

## Splitting

In [26]:
x = np.array([1,2,3,99,69,3,2,1])
np.split(x,[2,3,4])
# đếm lần lượt theo thứ tự

[array([1, 2]), array([3]), array([99]), array([69,  3,  2,  1])]

## Broadcasting and Vectorized operations

In [27]:
a = np.arange(3)

In [28]:
a

array([0, 1, 2])

In [29]:
a+5 #broadcasting

array([5, 6, 7])

In [31]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [44]:

a = np.array([[1],
              [2],
              [3]])
b = np.array([4,5,6])
a+b

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [46]:
#Nhân từng phần tử vị trí giống nhau
x = np.array([[1,2],
             [2,3]])
y = np.array([[2,3],
             [3,4]])
x*y 

array([[ 2,  6],
       [ 6, 12]])

In [47]:
#broadcasting
b*a

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

## Floor,Ceil,Rint: làm tròn số

In [100]:
np.floor(1.5) #làm tròn xuống

1.0

In [101]:
np.ceil(1.5) #làm tròn lên

2.0

In [104]:
np.rint(1.5) #làm tròn gần nhất

2.0

## Manipulating & Comparing 

### Aggregation: tập hợp

In [48]:
list_n = [1,2,3]
ll = np.array([list_n])

In [105]:
#np.sum >>> sum() : tổng các phần tử trong mảng
a = np.random.random(10000)
%timeit sum(a)
%timeit np.sum(a)

783 µs ± 2.67 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
7.73 µs ± 28.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [110]:
mat = np.array([[1,2,3],
              [4,5,6]])
np.sum(mat,axis = 1)

array([ 6, 15])

In [111]:
np.sum(mat,axis = 0)

array([5, 7, 9])

In [53]:
np.mean(a)

0.4991622609581787

In [54]:
np.max(a)

0.999981952435461

In [106]:
np.prod(ll) #tích các phẩn tử trong mảng

6

# STATISTICS : XSTK

In [55]:
#standard deviation: độ lệch chuẩn: căn bậc 2 của "phương sai"
# numpy.std(dự liệu)
#variance : phương sai : mức độ biến đổi của một tập dữ liệu
# numpy.var(dữ liệu)

In [56]:
dog_height = [600,470,170,430,400]
dog_height = np.array(dog_height)
np.std(dog_height)

139.79985693841036

In [57]:
np.var(dog_height)

19544.0

## Sorting Arrays
#### np.sort()

In [58]:
x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [59]:
np.argsort(x)

array([1, 0, 3, 2, 4], dtype=int64)

In [60]:
#đa chiều theo rows hoặc columns
np.random.seed(42)
mata = np.random.randint(0,10,size=(4,6))
mata

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [61]:
np.sort(mata,axis = 0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [62]:
np.sort(mata,axis = 1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

# Linear Algebra

In [2]:
A = np.array([[1,2,3],
             [4,5,6],
             [6,7,8]])
B = np.array([[1,2],
            [2,3],
            [3,4]])
A.dot(B)
#A.B

array([[14, 20],
       [32, 47],
       [44, 65]])

In [15]:
#TÍNH MA TRẬN NGHỊCH ĐẢO CỦA MA TRẬN A
np.linalg.inv(A)

array([[ 1.7156570e+15, -4.2891425e+15,  2.5734855e+15],
       [-3.4313140e+15,  8.5782850e+15, -5.1469710e+15],
       [ 1.7156570e+15, -4.2891425e+15,  2.5734855e+15]])

In [18]:
#TÍNH ĐỊNH THỨC CỦA MA TRẬN A
np.linalg.det(A)

-1.1657341758564207e-15

In [19]:
#GIẢI HỆ PHƯƠNG TRÌNH TUYẾN TÍNH AX = B TRONG ĐÓ A LÀ MA TRẬN HỆ SỐ VÀ B LÀ VECTO KẾT QUẢ
np.linalg.solve(A,B)

array([[ 8.578285e+14,  8.578285e+14],
       [-1.715657e+15, -1.715657e+15],
       [ 8.578285e+14,  8.578285e+14]])

In [22]:
#TÍNH TRỊ RIÊNG VÀ VECTO RIÊNG CỦA MA TRẬN A
np.linalg.eig(A)

(array([ 1.50000000e+01, -1.00000000e+00,  5.25462381e-16]),
 array([[ 2.49206599e-01,  8.32050294e-01,  4.08248290e-01],
        [ 5.69615084e-01, -8.25882719e-16, -8.16496581e-01],
        [ 7.83220740e-01, -5.54700196e-01,  4.08248290e-01]]))

In [23]:
#PHÂN TÍCH GIÁ TRỊ ĐƠN PHÂN RÃ (SVD)
np.linalg.svd(A)

(array([[-0.23498172,  0.91625348,  0.32444284],
        [-0.56747984,  0.14167532, -0.81110711],
        [-0.78914525, -0.37471012,  0.48666426]]),
 array([1.54611193e+01, 9.76621976e-01, 9.43299524e-17]),
 array([[-0.46825669, -0.57119923, -0.67414176],
        [-0.78362555, -0.08405223,  0.6155211 ],
        [-0.40824829,  0.81649658, -0.40824829]]))

In [28]:
#PHÂN TÍCH QR decomposition của ma trận A
np.linalg.qr(A)

(array([[-0.13736056,  0.93587869,  0.32444284],
        [-0.54944226,  0.20054543, -0.81110711],
        [-0.82416338, -0.28967674,  0.48666426]]),
 array([[-7.28010989e+00, -8.79107609e+00, -1.03020423e+01],
        [ 0.00000000e+00,  8.46747384e-01,  1.69349477e+00],
        [ 0.00000000e+00,  0.00000000e+00, -6.40115363e-16]]))

In [29]:
#MA TRẬN NGHỊCH ĐẢO MOORE-PENROSE ( MA TRẬN TỐI THIỂU BÌNH PHƯƠNG)
np.linalg.pinv(A)

array([[-0.72807018, -0.09649123,  0.3245614 ],
       [-0.07017544,  0.00877193,  0.06140351],
       [ 0.5877193 ,  0.11403509, -0.20175439]])

In [30]:
#HẠNG CỦA MA TRẬN
np.linalg.matrix_rank(A)

2

In [4]:
#Phép nhân ma trận =.dot()
A @ B

array([[14, 20],
       [32, 47],
       [44, 65]])

In [3]:
#Transpose ma trận chuyển vị
B.T

array([[1, 2, 3],
       [2, 3, 4]])

In [72]:
B.T@A

array([[27, 33, 39],
       [38, 47, 56]])

### Dot Product Example : tích vô hướng, còn với ma trận thì nhân ma trận


In [ ]:
#number of jars sold
np.random.seed(0)
sales_amounts = np.random.randint(20,size=(5,3))

In [93]:
#create weekly_sales Df
import pandas as pd
weekly_sales = pd.DataFrame(sales_amounts,index = ["Mon","Tues","Wed","Thurs","Fri"],columns = ["Almond Butter","Peanut Butter","Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [94]:
# create a price array
prices = np.array([[10,8,12]])
butter_prices = pd.DataFrame(prices,index = ["Price"],columns=["Almond Butter","Peanut Butter","Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [95]:
weekly_sales.shape, butter_prices.shape

((5, 3), (1, 3))

In [96]:
total_prices = weekly_sales.dot(butter_prices.T)
total_prices

Price
Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142

In [97]:
weekly_sales['Total'] = total_prices
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total
Mon               12             15              0    240
Tues               3              3              7    138
Wed                9             19             18    458
Thurs              4              6             12    232
Fri                1              6              7    142

### .Cross(mata,matb) : tích chéo 2 vecto 3 chiều (tích có hướng)

## .inner(a,b) : tích nội: giống .dot() tích vô hướng 2 vecto 1 chiều nhưng k nhân đc ma trận
## .outer(a,b) : tích ngoại: nhân mỗi phần tử trong a với từng phần tử trong b

In [3]:
a = np.array([[1,2],
               [2,4]])
b = np.array([3,4])
np.outer(a,b)

array([[ 3,  4],
       [ 6,  8],
       [ 6,  8],
       [12, 16]])

# Tính đa thức ( Polynomial)

In [12]:
p = np.array([4,5,6]) #đa thức 4x^2 + 5x + 6

array([4, 5, 6])

In [5]:
#TÍNH GIÁ TRỊ ĐA THỨC TẠI X
np.polyval(p,2)

32

In [6]:
#TÍNH NGHIỆM CỦA ĐA THỨC
np.roots(p)

array([-0.625+1.05326872j, -0.625-1.05326872j])

In [7]:
#TÍNH ĐẠO HÀM CỦA ĐA THỨC P
np.polyder(p)

array([8, 5])

In [8]:
#TÍNH NGUYÊN HÀM CỦA ĐA THỨC P
np.polyint(p)


array([1.33333333, 2.5       , 6.        , 0.        ])

In [11]:
#KHỚP ĐA THỨC
x = np.array([1,2])
y = np.array([3,4])
np.polyfit(x,y,2)
#0.1x^2 + 0.7x + 2.2 = y

C:\Users\Dell\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py:3505: RankWarning: Polyfit may be poorly conditioned
  exec(code_obj, self.user_global_ns, self.user_ns)


array([0.1, 0.7, 2.2])